[WIP] 3819 upgrade to rails 7
AgileVentures/WebsiteOne pull request #3837
Opened 2023-01-31 05:58 UTC by Florence-Njeri

#### Issue addressed

fixes #

#### Screenshots (if appropriate):

#### Testing

2023-02-02 01:54 UTC, mattlindsey commented
I think you can probably go right to version 7.0.4.2

2023-02-09 17:34 UTC, mattlindsey commented
Hi @Florence-Njeri.  I was bored and was looking at this and found a fix to many of the cucumber errors you are getting.

If you modify the file initializers/cucumber.rb to contain the following, many errors will disappear.  See change to line 11.

```
# frozen_string_literal: true

# Based on https://github.com/cucumber/cucumber-ruby/issues/1432
# HACK: this method was available in cucumber 3.1 and VCR relies on it to
# generate cassette names.
if Rails.env.test?
  Cucumber::Core::Test::Case.class_eval do
    def feature
      string = File.read(location.file)
      document = ::Gherkin::Parser.new.parse(string)
      document.feature
    end
  end
end
```

2023-02-09 17:35 UTC, mattlindsey commented
The problem above is referenced here:
https://github.com/cucumber/cucumber-ruby/issues/1432

2023-02-09 17:50 UTC, mattlindsey commented
I'm also thinking you can include the upgrade to ruby 3.2.1 if you want, if it doesn't have any issues with websiteone.  Or we can do a separate issue.
https://www.ruby-lang.org/en/news/2023/02/08/ruby-3-2-1-released/

2023-02-10 07:52 UTC, Florence-Njeri commented
Hi @mattlindsey, sure I'll include the Ruby upgrade too in this one too and also check the cucumber fix

2023-02-19 13:25 UTC, mattlindsey commented
I was playing with this and found a fix to some of the cucumber errors you are still getting.  Apparently 'to_date' and 'to_time' below are unnecessary and now cause errors.

Update lines 273 and 274 of 'features/step_definitions/event_steps.rb' from:
```
  expect(@start_date).to eq @tz.utc_to_local(@event.start_datetime).to_date.strftime('%Y-%m-%d')
  expect(@start_time).to eq @tz.utc_to_local(@event.start_datetime).to_time.strftime('%I:%M %p')
```
To:
```
  expect(@start_date).to eq @tz.utc_to_local(@event.start_datetime).strftime('%Y-%m-%d')
  expect(@start_time).to eq @tz.utc_to_local(@event.start_datetime).strftime('%I:%M %p')
```

2023-02-19 21:26 UTC, mattlindsey commented
Replace code starting at line 47 of the same file to eliminate another error:
```
Given('following events exist:') do |table|
  table.hashes.each do |hash|
    hash[:project_id] = Project.find_by(title: hash['project']).id unless hash['project'].blank?
    hash[:start_datetime] = Time.current.strftime('%c') if hash[:start_datetime] == 'TODAYS_DATE'
    hash.delete('project')
    hash[:repeat_ends] = false
    create(:event, hash)
  end
end
```

2023-02-20 09:34 UTC, Florence-Njeri commented
> Replace code starting at line 47 of the same file to eliminate another error:
> 
> ```
> Given('following events exist:') do |table|
>   table.hashes.each do |hash|
>     hash[:project_id] = Project.find_by(title: hash['project']).id unless hash['project'].blank?
>     hash[:start_datetime] = Time.current.strftime('%c') if hash[:start_datetime] == 'TODAYS_DATE'
>     hash.delete('project')
>     hash[:repeat_ends] = false
>     create(:event, hash)
>   end
> end
> ```

Thank you

2023-02-20 21:00 UTC, mattlindsey commented
Hi @Florence-Njeri.  This is looking good, but unfortunately I think that I found another issue.  We need to remove the 'compass-rails' gem from Gemfile because it is very old and discontinued, and doesn't work with latest ruby.  It gives an error on the file.exists method, so I think it needs to be taken out.  (I tried to find a fix for it, but couldn't.)

It is a CSS library, so we also need to remove where it is included in app/assets/stylesheets/application.sccs, and fix where it is used in the styles -- which might be a lot of places.  I found this, which may guide us on what to fix:  https://medium.com/@ayushya/migrating-from-compass-to-node-sass-4dadae9e8fb7.  And might need to add this: https://github.com/thoughtbot/bourbon.

Do you think you can try to do this?  Do you have any concerns?  I can help if you want.
Another option you can try is to not upgrade ruby, since compass-rails may still work with 3.0.5.  (Actually that may be a better option.  Then we can create a different Issue for removing compass-rails.)

2023-02-20 22:56 UTC, mattlindsey commented
Hi @Florence-Njeri.  Actually it turns out we are not using much of compass-rails, so it was very easy to remove.  Just:
- remove from Gemfile
- remove from first line in app/assets/stylesheets/application.scss
- remove the few uses of 'border-radius' from app/assets/stylesheets/layout/navbar.scss

2023-02-21 04:52 UTC, Florence-Njeri commented
> Hi @Florence-Njeri. Actually it turns out we are not using much of compass-rails, so it was very easy to remove. Just:
> 
> * remove from Gemfile
> * remove from first line in app/assets/stylesheets/application.scss
> * remove the few uses of 'border-radius' from app/assets/stylesheets/layout/navbar.scss

Hi @mattlindsey the error is still present

2023-02-21 11:31 UTC, mattlindsey commented
> 

Hi @Florence-Njeri.  Which error?  The only error left that I see is when running this: `bundle exec rspec ./spec/models/event_instance_spec.rb`

2023-02-21 12:43 UTC, mattlindsey commented
Looks like the 'coveralls' gem needs to be updated to this: `gem 'coveralls_reborn', require: false`

See: https://docs.coveralls.io/ruby-and-rails

2023-02-23 16:59 UTC, Florence-Njeri commented
> Looks like the 'coveralls' gem needs to be updated to this: `gem 'coveralls_reborn', require: false`
> 
> See: https://docs.coveralls.io/ruby-and-rails

Let me take a look

2023-02-24 18:54 UTC, mattlindsey commented
Looks like 'Time.mktime' need to be format:   Time.mktime(year, month, day, hour, min, sec_with_frac)

See: https://www.rubydoc.info/stdlib/core/Time.mktime

2023-02-24 23:13 UTC, mattlindsey requested changes

2023-02-24 23:13 UTC, mattlindsey commented on Gemfile
> +# gem 'compass-rails', '~> 4.0'
This line can be deleted.

2023-02-24 23:13 UTC, mattlindsey commented on app/assets/stylesheets/application.scss
> +// @import "compass/css3";
This line can be deleted.

2023-02-24 23:13 UTC, mattlindsey commented on Gemfile
> +gem 'nokogiri', '1.14.2'
I think we want: `gem 'nokogiri', '~> 1.14.2'`

Also, it seems to get 'bundle' to work on docker we need: `gem 'nokogiri', '~> 1.14.2', force_ruby_platform: true` (but doesn't work on my mac).

We can probably live with this for now by creating an Issue, and putting these instructions in the docker README.md.

2023-02-24 23:13 UTC, mattlindsey commented on Gemfile
> +gem 'youtube_rails', '~>1.2.3'
Put a space after the ~>

2023-02-25 00:16 UTC, mattlindsey requested changes

2023-02-25 00:16 UTC, mattlindsey commented on Dockerfile
> +FROM ruby:3.2.1-buster as base
Can you change this to: `FROM ruby:3.2.1 as base`
since the 'buster' version gives an error for me

2023-02-26 13:55 UTC, mattlindsey approved these changes
Looks good!

2023-02-26 13:58 UTC, merged